/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    sounds: Sound;
    soundMedia: SoundMedia;
    workshops: Workshop;
    imageMedia: ImageMedia;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Sound {
  id: string;
  name: string;
  workshop?: string | Workshop;
  lat: number;
  lng: number;
  audioFile: string | SoundMedia;
  description?: string;
  image?: string | ImageMedia;
  updatedAt: string;
  createdAt: string;
}
export interface Workshop {
  id: string;
  name?: string;
  updatedAt: string;
  createdAt: string;
}
export interface SoundMedia {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface ImageMedia {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
